### ISSUE TITLE
sorting by multiple columns?

### ISSUE THREAD

**Issue by ndeblauw** [Neurony/laravel-sort#2]
*feature request*
Hi Andrei,

Nice package - cleanly coded and easy to use. Is there a plan to add support for multiple sorting values,  e.g.

`/search-something?sort=company&direction=asc&sort=name&direction=asc`

would lead to sorting by company and within these subsets, records would be grouped by name, so Apple, Steve Jobs > Apple, Tim Cook > Microsoft, Bill Gates > Microsoft, Melinda Gates etc, well you get the picture

**Comment by zbiller** [comment]
Hi @ndeblauw 

I'm not so sure if this would be a good idea, as the package already supports sorting by relations, so having multiple sort columns support (some by direct fields, some by related ones), can impact the speed of parsing the query, not to say that it would become quite cumbersome and might be hard to use.

For the moment, if you require multiple sort columns, I suggest chaining `orderBy` methods to your query builder.

Thanks! :)
