### ISSUE TITLE
Attempting to sort users table by relation causes "this page is not working" with no log entry.

### ISSUE THREAD

**Issue by JamesPoel** [Neurony/laravel-sort#3]
I have users which have an associated company. Some users do not have a company.

If I add a global scope onto users which implements `->sorted( ['sort' => 'company.name', 'direction' => 'asc' ] );`, every page on my website stops working and there are no laravel.log entries; the php log shows `Allowed memory size of 536870912 bytes exhausted (tried to allocate 262144 bytes)`. It's presumably something to do with the Auth using the user model and getting itself into some kind of loop.

If I lose the global scope and implictly call `->sorted( ['sort' => 'company.name', 'direction' => 'asc' ] );` on my user list page, it works as expected.

**Comment by JamesPoel** [comment]
Oh, I have assigned all users a company and the problem persist. Is sorting by relationship broken?

**Comment by zbiller** [comment]
Hi @JamesPoel 

The `sorted` scope is not meant to be used as a global scope, because a global scope fires before the model can hook into its relationships.
